spring:
  application:
    name: config
  profiles:
    active: prod
  config:
    import: optional:configserver:http://localhost:8888

build:
  id: ${BUILD_ID}
  version: ${BUILD_VERSION}
  name: ${BUILD_NAME}

management:
  endpoints:
    web:
      exposure:
        include: refresh

server:
  port: 8000
