spring:
  application:
    name: user-service
  mongodb:
    uri: mongodb://localhost:27017/userdb
    database: userdb
  # datasource:
  #   url: jdbc:postgresql://localhost:5432/userdb
  #   username: postgres
  #   password: postgres
  # jpa:
  #   database: POSTGRESQL
  #   hibernate:
  #     ddl-auto: update
  #   show-sql: true
  #   database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081