# spring:
#   cloud:
#     gateway:
#       server:
#         webflux:
#           routes:
#               - id: product-service
#                 uri: lb://PRODUCT-SERVICE
#                 predicates:
#                   - Path=/products/**
#                 filters:
#                   - "RewritePath=/products(?<segment>/?.*),/api/products${segment}"
#               - id: user-service
#                 uri: lb://USER-SERVICE
#                 predicates:
#                   - Path=/users/**
#           filters:
#            - "RewritePath=/users(?<segment>/?.*),/api/users${segment}"
#               - id: order-service
#                 uri: lb://ORDER-SERVICE
#                 predicates:
#                   - Path=/orders/**, /cart/**
#           filters:
#            - "RewritePath=/(?<segment>.*),/api/${segment}"
#               - id: eureka-server
#                 uri: http://localhost:8761
#                 predicates:
#                   - Path=/eureka/main
#                 filters:
#                 - SetPath=/
#               - id: eureka-server-static
#                 uri: http://localhost:8761
#                 predicates:
#                   - Path=/eureka/**
# trusted-proxies: ".*"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

# Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      ecomBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: count_based

server:
  port: 8080

# logging:
#   level:
#     root: INFO
#     org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
#     org.springframework.cloud.gateway: TRACE
